# NumPy: Numerical Python

NumPy is a Python library used for numerical computing, providing support for arrays, matrices, and mathematical functions to operate on these arrays. It stands for Numerical Python.


In [88]:
! pip install numpy

In [89]:
import numpy as np

In [90]:
# Python also provides an array module which allows for more efficient arrays that store only a single data type
import array

In [91]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

## Characteristics of NumPy Arrays


NumPy is a powerful Python library used for numerical computing, especially when dealing with large, multi-dimensional arrays and matrices. Let's explore some of the key characteristics of NumPy arrays:

### Contiguous Memory Allocation

NumPy arrays are stored in contiguous memory blocks, which allows for efficient data access and manipulation. This is in contrast to Python lists, which store references to objects in memory and may not be contiguous.

### Broadcasting

NumPy arrays support broadcasting, which allows for element-wise operations between arrays of different shapes. This simplifies many common tasks in numerical computing and makes code more concise and readable.

### Indexing and Slicing

NumPy arrays support advanced indexing and slicing techniques, allowing for flexible and efficient access to elements and subsets of arrays. This includes boolean indexing, fancy indexing, and slicing along multiple dimensions.

### Extensive Functionality

NumPy provides a vast array of functionality for array manipulation, mathematical operations, linear algebra, Fourier transforms, random number generation, and more. This makes NumPy a versatile tool for a wide range of scientific and engineering applications.

In summary, NumPy arrays offer a powerful and efficient way to work with numerical data in Python, providing a rich set of features for data manipulation, computation, and analysis.


In [92]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

### Upcasting:
Upcasting refers to the conversion of data from a lower precision type to a higher precision type

### Type Casting:
Type casting, on the other hand, is the explicit conversion of data from one type to another

In [93]:
# here the highest order of data is string so all data in the output array is converted to strings
np.array([1,2,3,4,5,"sudh" , 4+8j,])

array(['1', '2', '3', '4', '5', 'sudh', '(4+8j)'], dtype='<U64')

In [94]:
# here the higest order i sfloat so all the data in the output is converted to the float
np.array([1,2,3,4.5,6.0])

array([1. , 2. , 3. , 4.5, 6. ])

In [95]:
# we can mention which data types should be the output array elements
np.array([1,2,3] , dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [96]:
# we can specify data type of each element seperatly
arr = np.array([(1,2) , (4,5)],dtype = [("a",'<i4'), ("b",'<i8')])

In [97]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [98]:
type(arr[0][0])

numpy.int32

In [99]:
type(arr[0][1])

numpy.int64

on the above examples either we can say upcast or typecast is been done

### Multi-dimensional

NumPy arrays can have multiple dimensions, allowing for the representation of complex data structures such as matrices and tensors. This makes NumPy especially useful for tasks like linear algebra and signal processing.

In [100]:
# dimension is 2*2
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [101]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [102]:
np.array([[1,3],[3,4],[7,8]])

array([[1, 3],
       [3, 4],
       [7, 8]])

In [103]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [104]:
# we can specify the dimension using the keyword ndimn
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

## Metrix

**ARRAY**

Definition: In NumPy, arrays are the fundamental data structure used for representing and working with multidimensional data.

Properties:
Arrays can have any number of dimensions (1D, 2D, 3D, etc.).
They are similar to Python lists but optimized for numerical operations.
Accessed using square brackets [ ]

**Matrices**

Definition: Matrices in NumPy are a specific type of array with exactly two dimensions.

Properties:
Always have two dimensions (rows and columns).
Can be created directly using the numpy.matrix class or by converting arrays using numpy.asarray.
Accessed using square brackets [ ].

**Conclusions**

Matrices are optimized for linear algebra operations like matrix multiplication, while arrays are more general-purpose.
Arrays support element-wise operations, broadcasting, and general array arithmetic.
Matrices support matrix multiplication (* operator) and other linear algebra operations.

In [105]:
arr  = np.array([[1,3],[3,4]])

In [106]:
type(arr) # array

numpy.ndarray

In [107]:
type(arr[0][1])

numpy.int32

In [108]:
mat = np.matrix(arr)
mat

matrix([[1, 3],
        [3, 4]])

## conversion to array

In [109]:
l = [3,4,5,76,7]

In [110]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [111]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [112]:
# asanyarray convert list to array since it not a type of array
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [113]:
# here metrix is already a subset of array so it won't be converted
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [114]:
# convert all type to array
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [115]:
# checking if array a subclass of metrix 
issubclass(np.ndarray,np.matrix )

False

In [116]:
# checking if metrix a subclass of array
issubclass(np.matrix,np.ndarray )

True

## copy

In [117]:
arr

array([[1, 3],
       [3, 4]])

In [118]:
# direct assigning of array to a valriable
a= arr # shallow copy

In [119]:
# copy the array and save in a variable
b = np.copy(arr) # deep copy

In [120]:
arr[0][0] = 67

In [121]:
arr

array([[67,  3],
       [ 3,  4]])

In [122]:
# change in arr is effected
a

array([[67,  3],
       [ 3,  4]])

In [123]:
# change in arr is not effected
b

array([[1, 3],
       [3, 4]])

In [124]:
arr[-1]

array([3, 4])

In [125]:
for i in arr:
    print(i)

[67  3]
[3 4]


## array using fromfunction

The fromfunction function in NumPy is used to construct an array by executing a function over each coordinate. It creates a new array by repeatedly calling a specified function, passing coordinate arrays as arguments, and using the returned values to fill in the array

In [126]:
type(np.fromfunction(lambda i , j :i==j,(4,4)))

numpy.ndarray

In [127]:
# i = row index, j = column index
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [128]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [129]:
np.fromfunction(lambda i , j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [130]:
np.fromfunction(lambda i , j :i/j,(3,3)) 
# i = 0, j = 0 : 0/0 = nan
# j = 0, i = {1,2} : i/j = inf, inf represents infinity

C:\Users\harsh\AppData\Local\Temp\ipykernel_14392\633141099.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i , j :i/j,(3,3))
C:\Users\harsh\AppData\Local\Temp\ipykernel_14392\633141099.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i , j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

## generator functions

Generator functions in NumPy are custom functions that produce values iteratively for creating NumPy arrays with specific patterns or sequences. These functions are commonly used in conjunction with NumPy's fromfunction function, which constructs arrays based on the output of the generator function

In [131]:
gen = (i*i for i in range(5))
gen

<generator object <genexpr> at 0x000002CEA2714BA0>

In [132]:
gen
for i in gen :
    print(i)

0
1
4
9
16


In [133]:
def test(x):
    yield x # yeild funcion helps to create any fucntion as generator function

In [134]:
test(5)

<generator object test at 0x000002CEA2714D60>

## conversion

In [135]:
# iterable to int element type
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

In [136]:
# string to int
np.fromstring('1,3,4,5,5' , sep = ',', dtype= int)

array([1, 3, 4, 5, 5])

In [137]:
np.fromstring("456 456 3454 34543" ,sep = ' ', dtype= complex)

array([  456.+0.j,   456.+0.j,  3454.+0.j, 34543.+0.j])

## features of any array

In [138]:
l = [3,4,5,6,7,8]

In [139]:
arr = np.array(l)

In [140]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])

In [141]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [142]:
type(arr)

numpy.ndarray

In [143]:
arr1.ndim # 3*4 array ie it has 2 dimensions x-axis and y-axis

2

In [144]:
arr1.size # total number of elements

12

In [145]:
arr1.shape # metrix row*column


(3, 4)

In [146]:
arr1.dtype

dtype('int32')

In [147]:
arr

array([3, 4, 5, 6, 7, 8])

In [148]:
arr.size

6

In [149]:
arr.ndim

1

In [150]:
arr.shape

(6,)

In [151]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [152]:
arr2


array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [153]:
arr2.size

16

In [154]:
arr2.ndim

3

In [155]:
arr2.shape

(2, 2, 4)

In [156]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [157]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [158]:
arr4.ndim

4

In [159]:
arr4.shape

(1, 4, 2, 4)

## Function in array

In [160]:
# list(range(6.6,9,.3)) # TypeError: 'float' object cannot be interpreted as an integer

In [161]:
# range
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [162]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [163]:
# linespace give start = 1, end = 10, number of elements = 5
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [164]:
# 1d zero array with 5 elements
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [165]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [166]:
np.ones(4)

array([1., 1., 1., 1.])

In [167]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [168]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [169]:
np.empty((3,4))

array([[1.52467094e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.20953760e-312, 2.95194079e+179, 1.15980983e-046,
        1.10957135e-047],
       [1.68620544e-051, 1.68606834e+160, 1.83127100e-076,
        1.48474761e-076]])

In [170]:
# identity metrix of 3*3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [171]:
# [1,6] the starting point is a list here not a single point
# 4 ending point both the 1 and 6 should stay inside [1,4) and (4,6]
# 5 there is only 5 elements
# endpoint = False exclude the last element ie 4
# axis = 0 row wise
np.linspace([1,6],4,5,endpoint=False,axis=0)

array([[1. , 6. ],
       [1.6, 5.6],
       [2.2, 5.2],
       [2.8, 4.8],
       [3.4, 4.4]])

In [172]:
# column wise
np.linspace([1,6],4,5,endpoint=False,axis=1)

array([[1. , 1.6, 2.2, 2.8, 3.4],
       [6. , 5.6, 5.2, 4.8, 4.4]])

In [173]:
# log(100) = 2
np.logspace([2], [3], 5,  axis = 0)

array([[ 100.        ],
       [ 177.827941  ],
       [ 316.22776602],
       [ 562.34132519],
       [1000.        ]])

In [174]:
d = np.linspace(4,7,40)

In [175]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [176]:
d.ndim

1

In [177]:
d.shape

(40,)

In [178]:
# we can reshape the array according to our fesibility
# NOTE the total number of elemets should be same
# eg : 2*4 array has 8 elments so it can't be reshaped to 3*3 which has 9 elements
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [179]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [180]:
np.logspace(2,5,10)


array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [181]:
# random number of 1d array wiht 3 elements based on normal distribution
np.random.rand(3)

array([0.68950262, 0.58215763, 0.31206232])

In [182]:
# random number of 1d array wiht 3 elements from standartd normal distribution
np.random.randn(3)

array([-1.24206231, -1.03904679,  1.23986432])

In [183]:
np.random.randn(2,2,3)

array([[[ 0.10993289, -1.88112906,  1.06925216],
        [-2.01601773, -0.51533817,  2.08369695]],

       [[-1.32413508,  0.05150499, -0.78003899],
        [ 0.0798076 ,  0.94242032,  0.4144893 ]]])

In [184]:
# randint give integer random number
np.random.randint(5,60, (4,4))

array([[ 6, 52, 32, 26],
       [52, 59, 39, 14],
       [59, 14, 31, 51],
       [49, 35, 43, 31]])

In [185]:
np.random.randn(2,2,3)

array([[[ 0.50474667, -1.95989367, -0.20598278],
        [ 1.79120682, -1.04593832,  0.03842083]],

       [[-2.22998377, -0.47014674, -0.81803207],
        [-0.19753718, -0.26323919, -2.64217602]]])

In [186]:
arr = np.random.randint(3,9, ( 3,3))

In [187]:
arr

array([[5, 6, 7],
       [5, 3, 5],
       [8, 5, 3]])

In [188]:
arr.reshape(1,9)

array([[5, 6, 7, 5, 3, 5, 8, 5, 3]])

In [189]:
arr.reshape(9,1)

array([[5],
       [6],
       [7],
       [5],
       [3],
       [5],
       [8],
       [5],
       [3]])

In [190]:
arr.reshape(1,1,9)

array([[[5, 6, 7, 5, 3, 5, 8, 5, 3]]])

In [191]:
arr.reshape(3,3,1)

array([[[5],
        [6],
        [7]],

       [[5],
        [3],
        [5]],

       [[8],
        [5],
        [3]]])

In [192]:
arr.reshape(3,-198979)

array([[5, 6, 7],
       [5, 3, 5],
       [8, 5, 3]])

In [193]:
arr.reshape(1,-145654656)

array([[5, 6, 7, 5, 3, 5, 8, 5, 3]])

In [194]:
arr

array([[5, 6, 7],
       [5, 3, 5],
       [8, 5, 3]])

In [195]:
arr.max()

8

In [196]:
arr.min()

3

In [197]:
arr = np.random.randint(4,100, (5,5))

In [198]:
arr

array([[27, 94, 12, 32, 51],
       [61, 87, 39,  8, 46],
       [80, 52, 61, 93, 35],
       [85, 21, 79, 87, 46],
       [83, 81, 98, 62, 66]])

In [199]:
arr[3: , 3:]

array([[87, 46],
       [62, 66]])

In [200]:
arr[:,[1,3]]

array([[94, 32],
       [87,  8],
       [52, 93],
       [21, 87],
       [81, 62]])

In [201]:
arr

array([[27, 94, 12, 32, 51],
       [61, 87, 39,  8, 46],
       [80, 52, 61, 93, 35],
       [85, 21, 79, 87, 46],
       [83, 81, 98, 62, 66]])

In [202]:
arr[arr>10]

array([27, 94, 12, 32, 51, 61, 87, 39, 46, 80, 52, 61, 93, 35, 85, 21, 79,
       87, 46, 83, 81, 98, 62, 66])

In [203]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [204]:
arr

array([[27, 94, 12, 32, 51],
       [61, 87, 39,  8, 46],
       [80, 52, 61, 93, 35],
       [85, 21, 79, 87, 46],
       [83, 81, 98, 62, 66]])

In [205]:
# elementwise multiplication
arr * arr

array([[ 729, 8836,  144, 1024, 2601],
       [3721, 7569, 1521,   64, 2116],
       [6400, 2704, 3721, 8649, 1225],
       [7225,  441, 6241, 7569, 2116],
       [6889, 6561, 9604, 3844, 4356]])

In [206]:
arr1 = np.random.randint(2,4,(3,3))

In [207]:
arr2 = np.random.randint(2,4,(3,3))

In [208]:
arr1

array([[2, 3, 2],
       [2, 2, 2],
       [2, 3, 3]])

In [209]:
arr2

array([[3, 3, 3],
       [2, 2, 2],
       [3, 3, 2]])

In [210]:
arr1*arr2

array([[6, 9, 6],
       [4, 4, 4],
       [6, 9, 6]])

In [211]:
# metrix multiplication
arr1@arr2

array([[18, 18, 16],
       [16, 16, 14],
       [21, 21, 18]])

### Broadcasting

In [212]:
arr/0

C:\Users\harsh\AppData\Local\Temp\ipykernel_14392\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [213]:
arr**2

array([[ 729, 8836,  144, 1024, 2601],
       [3721, 7569, 1521,   64, 2116],
       [6400, 2704, 3721, 8649, 1225],
       [7225,  441, 6241, 7569, 2116],
       [6889, 6561, 9604, 3844, 4356]])

In [214]:
arr = np.zeros((3,4))

In [215]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [216]:
a = np.array([1,2,3,5])

In [217]:
a


array([1, 2, 3, 5])

In [218]:
# rowwise
arr + a 

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [219]:
arr+ 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [220]:
b = np.array([5,6,7])

In [221]:
b

array([5, 6, 7])

In [222]:
# columnwise
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [223]:
b

array([5, 6, 7])

In [224]:
b = np.array([[5,6,7]])

In [225]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [226]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### math fcuncation

In [227]:
arr = np.random.rand(5,4)

In [228]:
arr

array([[0.68561612, 0.9447321 , 0.55638337, 0.61599931],
       [0.30716655, 0.79533551, 0.56682945, 0.5710707 ],
       [0.22854951, 0.93486021, 0.21105252, 0.03649737],
       [0.47194919, 0.95428605, 0.23707331, 0.79446813],
       [0.32881196, 0.33946011, 0.34696565, 0.48208837]])

In [229]:
np.sqrt(arr)

array([[0.82801939, 0.9719733 , 0.7459111 , 0.78485624],
       [0.55422608, 0.89181585, 0.75288077, 0.7556922 ],
       [0.47806853, 0.9668817 , 0.45940453, 0.19104286],
       [0.68698558, 0.97687566, 0.48690175, 0.89132942],
       [0.57342128, 0.58263205, 0.5890379 , 0.69432584]])

In [230]:
np.exp(arr)

array([[1.98499445, 2.5721242 , 1.74435239, 1.85150591],
       [1.35956738, 2.21518409, 1.76266955, 1.77016135],
       [1.25677575, 2.54685741, 1.23497722, 1.03717158],
       [1.60311592, 2.59681593, 1.26753404, 2.21326351],
       [1.38931659, 1.40418928, 1.41476813, 1.61945289]])

In [231]:
np.log10(arr)

array([[-0.16391898, -0.02469133, -0.25462586, -0.21041977],
       [-0.51262609, -0.09944963, -0.24654759, -0.24331012],
       [-0.6410197 , -0.02925332, -0.67560946, -1.4377384 ],
       [-0.32610476, -0.02032142, -0.62511734, -0.09992352],
       [-0.48305239, -0.46921125, -0.45971352, -0.31687335]])

In [232]:
arr1 = np.random.randint(2,5, (5,5))

In [233]:
np.log10(arr1)

array([[0.30103   , 0.30103   , 0.30103   , 0.30103   , 0.47712125],
       [0.47712125, 0.60205999, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.30103   , 0.60205999, 0.47712125, 0.47712125],
       [0.60205999, 0.30103   , 0.30103   , 0.47712125, 0.60205999],
       [0.30103   , 0.47712125, 0.30103   , 0.60205999, 0.30103   ]])

In [234]:
arr1

array([[2, 2, 2, 2, 3],
       [3, 4, 3, 3, 3],
       [4, 2, 4, 3, 3],
       [4, 2, 2, 3, 4],
       [2, 3, 2, 4, 2]])

### seed

In [235]:
# seed helps to get consistant random numbers everytime we run the code
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])